GET https://editor.p5js.org/editor/rob.clouth/projects/Y7eLtQ9Ct

###
GET http://localhost:3000/api/webhook
Content-Type: application/json

{
  "message": {
    "chat": {
      "id": "1"
    },
    "text": "qwe"
  }
}