GET https://editor.p5js.org/editor/rob.clouth/projects/Y7eLtQ9Ct

###
GET http://localhost:3000/api/webhook
Content-Type: application/json

{
  "message": {
    "chat": {
      "id": "1"
    },
    "text": "qwe"
  }
}

###
POST https://api.telegram.org/bot5575192233:AAFKgg33RWKbqMpOBfA5eZm6CRILJh4qYEI/setWebhook
Content-type: application/json

{"url": "https://2a0f-83-32-25-129.ngrok.io/api/webhook"}

###
POST https://api.telegram.org/bot5575192233:AAFKgg33RWKbqMpOBfA5eZm6CRILJh4qYEI/setWebhook
Content-type: application/json

{"url": "https://stickergen.vercel.app/api/webhook"}